// Code generated by optimus. DO NOT EDIT.
package config

import (
	"time"
)

type ServerConfigOption func(*ServerConfig)

// NewServerConfig creates a new ServerConfig with defaults and applies options.
func NewServerConfig(opts ...ServerConfigOption) *ServerConfig {
	c := &ServerConfig{
		Host:      "localhost",
		Port:      8080,
		Timeout:   10 * time.Second,
		EnableLog: true,
	}
	c.Apply(opts...)
	return c
}

// Apply applies options to the config
func (c *ServerConfig) Apply(opts ...ServerConfigOption) {
	for _, opt := range opts {
		opt(c)
	}
}

// Host 默认为 localhost
// 注意：string 类型，生成器会自动给它加引号
// WithHost sets the Host field.
func WithHost(v string) ServerConfigOption {
	return func(c *ServerConfig) {
		c.Host = v
	}
}

// Port 默认为 8080
// 注意：int 类型，生成器直接使用原值
// WithPort sets the Port field.
func WithPort(v int) ServerConfigOption {
	return func(c *ServerConfig) {
		c.Port = v
	}
}

// Timeout 默认为 10秒
// 注意：这里我们直接写 Go 代码片段，生成器会把它复制过去
// WithTimeout sets the Timeout field.
func WithTimeout(v time.Duration) ServerConfigOption {
	return func(c *ServerConfig) {
		c.Timeout = v
	}
}

// EnableLog 默认为 true
// WithEnableLog sets the EnableLog field.
func WithEnableLog(v bool) ServerConfigOption {
	return func(c *ServerConfig) {
		c.EnableLog = v
	}
}

// Whitelist 切片暂不支持 default（因为切片初始化比较复杂），保持为空
// AddWhitelist appends values to Whitelist slice.
func AddWhitelist(v ...string) ServerConfigOption {
	return func(c *ServerConfig) {
		c.Whitelist = append(c.Whitelist, v...)
	}
}
