// Code generated by optimus. DO NOT EDIT.
package config

import (
	"time"
)

type ServerConfigOption func(*ServerConfig)

// Apply applies options to the config
func (c *ServerConfig) Apply(opts ...ServerConfigOption) {
	for _, opt := range opts {
		opt(c)
	}
}

// Host is the binding address
// WithHost sets the Host field.
func WithHost(v string) ServerConfigOption {
	return func(c *ServerConfig) {
		c.Host = v
	}
}

// Port 监听端口
// 默认 8080
// WithPort sets the Port field.
func WithPort(v int) ServerConfigOption {
	return func(c *ServerConfig) {
		c.Port = v
	}
}

// Timeout 请求超时时间
// WithTimeout sets the Timeout field.
func WithTimeout(v time.Duration) ServerConfigOption {
	return func(c *ServerConfig) {
		c.Timeout = v
	}
}

// Whitelist 这里的 []string 会自动生成 AddWhitelist 方法
// AddWhitelist appends values to Whitelist slice.
func AddWhitelist(v ...string) ServerConfigOption {
	return func(c *ServerConfig) {
		c.Whitelist = append(c.Whitelist, v...)
	}
}

// TLS 这里的 opt:"WithSecure" 表示生成的函数改名叫 WithSecure
// WithSecure sets the TLS field.
func WithSecure(v bool) ServerConfigOption {
	return func(c *ServerConfig) {
		c.TLS = v
	}
}
